### ISSUE TITLE
Apollo Client 2.0 support.

### ISSUE THREAD

**Issue by deden** [siteone/apollo-mocknetworkinterface#1]
Do you have any plan for Apollo Client 2.0?

**Comment by adambisek** [comment]
It's in plan, but don't have time at the moment.
Did you try it? What's specific issues wit Apollo 2.0?

**Comment by adambisek** [comment]
Figured out what's needed, i'll release for Apollo 2.0 in next few days.

**Comment by adambisek** [comment]
Now supporting Apollo 2.
