### ISSUE TITLE
should render without exploding (5040ms)

### ISSUE THREAD

**Issue by shashikantChetu** [siteone/apollo-mocknetworkinterface#3]
We have issue related to set time out in jest set up. we have run test cases.
error:
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

``` const mockedNetworkFetch = createMockedNetworkFetch(createResponse, { timeout: 30000 }); // you can simulate network latency
const client = new ApolloClient({
  link: createHttpLink({ uri: 'https://URL/graphql', fetch: mockedNetworkFetch }),
  cache: new InMemoryCache(),
});

it('should render without exploding', (done) => {
  const component = renderer.create((
    <ApolloProvider client={client}>
      <div>
        <TestComponentWithApollo />
      </div>
    </ApolloProvider>
  ));
})```

**Comment by adambisek** [comment]
This issue is related to jest, not this library.
But for me always worked add to beginning of test:
`
jasmine.DEFAULT_TIMEOUT_INTERVAL = 30000;
`
https://github.com/facebook/jest/issues/5055
